# Generated by Django 2.1 on 2020-04-16 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maipassport.core.models
import maipassport.users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('pub_id', maipassport.core.models.AutoPubIDField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='Public Id')),
                ('api_token', models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='API Token')),
                ('public_sign_key', models.CharField(max_length=511, unique=True, verbose_name='API Verify Key')),
                ('alias_id', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Alias ID')),
                ('scan_enabled', models.BooleanField(default=False)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppUserPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('pub_id', maipassport.core.models.AutoPubIDField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='Public Id')),
                ('permission', models.PositiveSmallIntegerField(choices=[(0, 'Approach check'), (1, 'Health check'), (2, 'Visitor check'), (3, 'Transfer point')])),
                ('app_user', models.ManyToManyField(to='users.AppUser', verbose_name='app_users')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('pub_id', maipassport.core.models.AutoPubIDField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='Public Id')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'On Work'), (1, 'Get off work'), (2, 'Leave'), (3, 'Fieldwork'), (4, 'Business trip')], default=1)),
                ('remote_work', models.BooleanField(default=False)),
                ('app_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.AppUser')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('pub_id', maipassport.core.models.AutoPubIDField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='Public ID')),
                ('api_token', models.CharField(db_index=True, default=maipassport.users.models.token_generator, max_length=255, unique=True, verbose_name='API Token')),
                ('public_sign_key', models.CharField(max_length=511, unique=True, verbose_name='API Verify Key')),
                ('name', models.CharField(max_length=32, verbose_name='Display Name')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
            options={
                'verbose_name': 'app_user',
                'verbose_name_plural': 'app_users',
            },
        ),
        migrations.CreateModel(
            name='DeviceUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('pub_id', maipassport.core.models.AutoPubIDField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='Public ID')),
                ('api_token', models.CharField(db_index=True, default=maipassport.users.models.token_generator, max_length=255, unique=True, verbose_name='API Token')),
                ('public_sign_key', models.CharField(max_length=511, unique=True, verbose_name='API Verify Key')),
                ('name', models.CharField(max_length=32, verbose_name='Display Name')),
            ],
            options={
                'verbose_name': 'app_user',
                'verbose_name_plural': 'app_users',
            },
        ),
        migrations.CreateModel(
            name='HealthCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('pub_id', maipassport.core.models.AutoPubIDField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='Public Id')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, 'Wait Measure'), (1, 'Normal'), (2, 'Danger')], default=0)),
                ('app_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.AppUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
