# Generated by Django 2.1 on 2020-04-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_appuser_token_expire_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='token_expire_time',
        ),
    ]
