# Generated by Django 2.1 on 2020-04-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_appuser_token_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='token_expire_time',
            field=models.DateTimeField(null=True),
        ),
    ]
