# Generated by Django 2.1 on 2020-04-29 09:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_appuser_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='user_detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
