# Generated by Django 2.2.9 on 2020-05-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_appuser_user_picture_b64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcode',
            name='code',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Wait Measure'), (1, 'Normal'), (2, 'Danger'), (3, 'Risky'), (9, 'Unfilled')], default=9),
        ),
    ]
