# Generated by Django 2.2.9 on 2020-05-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200507_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='user_picture_b64',
        ),
        migrations.AddField(
            model_name='appuser',
            name='user_picture_local',
            field=models.URLField(null=True),
        ),
    ]
