# Generated by Django 2.2.9 on 2020-09-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200512_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancestatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'At Work'), (1, 'Get off work'), (2, 'Leave'), (3, 'Fieldwork'), (4, 'Business trip')], default=1),
        ),
        migrations.AlterField(
            model_name='healthcode',
            name='code',
            field=models.PositiveSmallIntegerField(choices=[(0, 'To be Measured'), (1, 'Normal'), (2, 'Danger'), (3, 'High Risk'), (9, 'Unfilled')], default=9),
        ),
    ]
