# Generated by Django 2.2.9 on 2020-09-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200911_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='qr_code_url',
            field=models.URLField(null=True),
        ),
    ]
