# Generated by Django 2.2.9 on 2021-10-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200917_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='emp_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
