# Generated by Django 2.1 on 2020-04-20 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20200416_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompanytable',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Department'),
        ),
        migrations.AlterField(
            model_name='usercompanytable',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Title'),
        ),
    ]
