# Generated by Django 2.2.9 on 2020-05-10 16:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_place_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
