# Generated by Django 2.2.9 on 2020-05-19 03:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import maipassport.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200512_1544'),
        ('companies', '0008_place_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCompanyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', maipassport.core.models.AutoPubIDField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='Public Id')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDefaultPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', maipassport.core.models.AutoPubIDField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='Public Id')),
                ('place_code', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='AddRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('pub_id', maipassport.core.models.AutoPubIDField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='Public Id')),
                ('agree', models.BooleanField(default=False)),
                ('add_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.AddCompanyTag')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_user', to='users.AppUser')),
                ('agree_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agree_user', to='users.AppUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
