# Generated by Django 2.2.9 on 2020-05-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20200520_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addrequest',
            name='agree',
        ),
        migrations.AddField(
            model_name='addrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Wait audit'), (1, 'Agree'), (2, 'Cancel')], default=0),
        ),
    ]
