# Generated by Django 2.2.9 on 2020-05-22 06:18

from django.db import migrations, models
import django.db.models.deletion
import maipassport.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20200520_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('pub_id', maipassport.core.models.AutoPubIDField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='Public Id')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user_company_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.UserCompanyTable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
