# Generated by Django 2.2.9 on 2020-06-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_auto_20200522_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompanytable',
            name='department_manage_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
