# Generated by Django 2.2.9 on 2020-09-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_usercompanytable_department_manage_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
