# Generated by Django 2.2.9 on 2020-09-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_newcompanyapply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='tax_number',
            new_name='tax_id_number',
        ),
    ]
