# Generated by Django 2.2.9 on 2020-09-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_auto_20200915_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcompanytag',
            name='qr_code_upload',
            field=models.BooleanField(default=False),
        ),
    ]
