# Generated by Django 2.2.9 on 2020-09-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_addcompanytag_qr_code_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='serial_num',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
