# Generated by Django 2.2.9 on 2020-09-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_place_serial_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='update_health_code',
            field=models.BooleanField(default=False),
        ),
    ]
