# Generated by Django 2.2.9 on 2021-05-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_place_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='company_verify',
            field=models.BooleanField(default=False),
        ),
    ]
