# Generated by Django 2.2.9 on 2021-05-18 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200917_1345'),
        ('companies', '0024_place_company_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.AppUser'),
        ),
    ]
