# Generated by Django 2.2.9 on 2021-05-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_place_place_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_contact_phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
