# Generated by Django 2.2.9 on 2021-05-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_place_place_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='company_verify',
        ),
    ]
