# Generated by Django 2.2.9 on 2021-05-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_place_company_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='place_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='verification_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
