# Generated by Django 2.2.9 on 2021-05-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0032_auto_20210520_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='default_show',
            field=models.BooleanField(default=False),
        ),
    ]
