# Generated by Django 2.2.9 on 2021-05-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0036_auto_20210531_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Backend User Login'), (1, 'User Privilege changed: Manager'), (2, 'User Privilege changes: Department Manager'), (3, 'User Privilege changed: Healthcode'), (4, 'New Place Added'), (5, 'Place Certification: PASS'), (6, 'Place Certification: FAILED'), (7, 'User Request: Company Join'), (8, 'User Request: Company Join PASS'), (9, 'User Request: Company Join FAILED'), (10, 'User Request: PDF Download')], default=None),
        ),
    ]
