# Generated by Django 2.2.9 on 2021-06-01 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0037_auto_20210531_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
