# Generated by Django 2.2.9 on 2021-06-01 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0038_auto_20210601_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionlog',
            old_name='status',
            new_name='log_type',
        ),
    ]
