# Generated by Django 2.2.9 on 2021-10-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0040_auto_20210601_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='log_type',
            field=models.CharField(choices=[('Backend_User_Login', 'Backend User Login'), ('User_Privilege_Changed_Manager', 'User Privilege changed: Manager'), ('User_Privilege_Changed_Dep_Manager', 'User Privilege changes: Department Manager'), ('User_Privilege_Changed_Healthcode', 'User Privilege changed: Healthcode'), ('Place_Add', 'New Place Added'), ('Place_Pass', 'Place Certification: PASS'), ('Place_Not_Pass', 'Place Certification: FAILED'), ('Company_Add', 'User Request: Company Join'), ('Company_Pass', 'User Request: Company Join PASS'), ('Company_Not_Pass', 'User Request: Company Join FAILED'), ('Place_PDF_Download', 'User Request: PDF Download')], default=None, max_length=60),
        ),
    ]
