# Generated by Django 2.2.9 on 2021-10-06 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0041_auto_20211006_1615'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='place',
        #     name='address',
        # ),
    ]
