# Generated by Django 2.2.9 on 2021-10-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0042_remove_place_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='place_checkin',
            field=models.BooleanField(default=False),
        ),
    ]
