# Generated by Django 2.2.9 on 2021-10-08 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0043_auto_20211006_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
    ]
