# Generated by Django 2.1 on 2020-04-19 11:28

from django.db import migrations, models
import maipassport.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20200417_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('pub_id', maipassport.core.models.AutoPubIDField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='Public Id')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='health_code',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Wait Measure'), (1, 'Normal'), (2, 'Danger'), (3, 'Risky')], default=0),
        ),
    ]
