# Generated by Django 2.1 on 2020-04-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20200419_1928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
