# Generated by Django 2.1 on 2020-04-21 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200420_2241'),
        ('companies', '0004_place_scan_enabled'),
        ('records', '0005_delete_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='app_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.AppUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitorregistration',
            name='app_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.AppUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitorregistration',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='companies.Company'),
            preserve_default=False,
        ),
    ]
