# Generated by Django 2.1 on 2020-04-24 08:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20200421_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approachrecord',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='placeentryrecord',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
