# Generated by Django 2.1 on 2020-04-26 14:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20200424_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
