# Generated by Django 2.1 on 2020-04-29 03:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_remove_attendancerecord_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
