# Generated by Django 2.1 on 2020-04-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_attendancerecord_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='attendance_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'On Work'), (1, 'Get off work'), (2, 'Leave'), (3, 'Fieldwork'), (4, 'Business trip')], default=0),
            preserve_default=False,
        ),
    ]
