# Generated by Django 2.2.9 on 2021-09-11 03:12

from django.db import migrations, models
import maipassport.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_auto_20200911_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='NTPCCalender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', maipassport.core.models.AutoPubIDField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='Public Id')),
                ('date', models.DateField(max_length=100)),
                ('isHoliday', models.BooleanField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
