# Generated by Django 2.2.9 on 2021-09-29 07:09

from django.db import migrations, models
import django.db.models.deletion
import maipassport.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200917_1345'),
        ('records', '0016_ntpccalender'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('pub_id', maipassport.core.models.AutoPubIDField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='Public Id')),
                ('image', models.FileField(upload_to='')),
                ('image_data', models.BinaryField(null=True)),
                ('app_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.AppUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RapidTestRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('pub_id', maipassport.core.models.AutoPubIDField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='Public Id')),
                ('image', models.FileField(upload_to='')),
                ('image_data', models.BinaryField(null=True)),
                ('app_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.AppUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CovidHistoryRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('pub_id', maipassport.core.models.AutoPubIDField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='Public Id')),
                ('image', models.FileField(upload_to='')),
                ('image_data', models.BinaryField(null=True)),
                ('app_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.AppUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
