# Generated by Django 2.2.9 on 2021-09-29 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_covidhistoryrecord_rapidtestrecord_vacrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidhistoryrecord',
            name='image',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='rapidtestrecord',
            name='image',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='vacrecord',
            name='image',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg'])]),
        ),
    ]
