# Generated by Django 2.2.9 on 2021-10-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_auto_20210929_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidhistoryrecord',
            name='image_url',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='rapidtestrecord',
            name='image_url',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='vacrecord',
            name='image_url',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
