# Generated by Django 2.2.9 on 2021-10-06 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_auto_20211006_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidhistoryrecord',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='rapidtestrecord',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='vacrecord',
            name='image_url',
        ),
    ]
