# Generated by Django 2.2.9 on 2021-10-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_auto_20211006_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidhistoryrecord',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rapidtestrecord',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vacrecord',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
